# Setup
title:               Ty Martz
tagline:             'Making Headway in Analytics & Forecasting'
description:         'Much a do about too much'
url:                 https://ty-martz.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty
markdown:            kramdown
paginate:            5
paginate_path:       "/page:num/"

# About/contact
author:
  name: 'Ty Martz'
  email: 'jacksontmartz[at]gmail[dot]com'
  github: ty-martz
  linkedin: ty-martz
  google_analytics_id: G-ZTQ2WXE508
  bio: Making Headway in Analytics & Forecasting

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-ZTQ2WXE508
